[tool.poetry]
name = "automated-docker-images"
version = "0.1.0"
description = "\"Automate docker images for EA\""
authors = ["witkowj3 <jakub.witkowski.jw1@roche.com>"]
readme = "README.md"
packages = [{include = "automated_docker_images"}]

[tool.poetry.dependencies]
python = "~3.8"
scikit-learn = "^1.2.2"
joblib = "^1.2.0"
kserve = "^0.10.1.1"
pathlib = "^1.0.1"
typing = "3.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
